name: Matrix Test the analyze and test workflow

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
        description: 'The module to process.'
      pip-list:
        required: false
        type: string
        default: ''
        description: 'Additional pip packages to be installed.'
      package-list:
        required: false
        type: string
        default: ''
        description: 'Additional OS packages to be installed.'
      lint:
        required: false
        type: boolean
        default: true
      unit-test:
        required: false
        type: boolean
        default: true
      function-test:
        required: false
        type: boolean
        default: true
      integration-test:
        required: false
        type: boolean
        default: true
      code-coverage:
        required: false
        type: boolean
        default: true
      coveralls-upload:
        required: false
        type: boolean
        default: true
      codecov-upload:
        required: false
        type: boolean
        default: true
      sonar-scan:
        required: false
        type: boolean
        default: true
    secrets:
      COVERALLS_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  run:

    strategy:
      fail-fast: false
      matrix:
        #python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14.0-rc.2"]
        #weewx-version: ["5.0.0", "5.1.0", "branch-master", "branch-development"]
        python-version: ["3.13"]
        weewx-version: ["5.1.0"]

    #uses: weewx-extensions/development_tools/.github/workflows/analyze-test.yml@v2
    uses: ./.github/workflows/analyze-test.yml
    with:
      module-name: ${{inputs.module-name}}
      python-version: ${{matrix.python-version}}
      weewx-version: ${{matrix.weewx-version}}
      latest-python-version: '3.13'
      latest-weewx-version: '5.1.0'
      pip-list: ${{inputs.pip-list}}
      package-list: ${{inputs.package-list}}
      lint: ${{inputs.lint}}
      unit-test: ${{inputs.unit-test}}
      function-test: ${{inputs.function-test}}
      integration-test: ${{inputs.integration-test}}
      code-coverage: ${{inputs.code-coverage}}
      coveralls-upload: ${{inputs.coveralls-upload}}
      codecov-upload: ${{inputs.codecov-upload}}
      sonar-scan: ${{inputs.sonar-scan}}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
