name: Matrix Test the analyze and test workflow

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
        description: 'The module to process.'
      pip-list:
        required: false
        type: string
        default: ''
        description: 'Additional pip packages to be installed.'
      package-list:
        required: false
        type: string
        default: ''
        description: 'Additional OS packages to be installed.'
      lint:
        required: false
        type: boolean
        default: true
      unit-test:
        required: false
        type: boolean
        default: true
      function-test:
        required: false
        type: boolean
        default: true
      integration-test:
        required: false
        type: boolean
        default: true
      code-coverage:
        required: false
        type: boolean
        default: true
      coveralls-upload:
        required: false
        type: boolean
        default: true
      codecov-upload:
        required: false
        type: boolean
        default: true
      sonar-scan:
        required: false
        type: boolean
        default: true
      # These are not expected to be passed in
      # They are here so that I can define the values once
      latest-os-version:
        required: false
        type: string
        default: 'ubuntu-24.04'
      latest-python-version:
        required: false
        type: string
        default: '3.13'
    secrets:
      CODECOV_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  run:

    strategy:
      fail-fast: false
      matrix:
        os-version: ["ubuntu-24.04", "ubuntu-22.04"]
        # Specify the exact minimum supported Python version, ie 3.9.13 and not 3.9
        # Note, 3.9.13 is the oldest version that runs via github actions
        python-version: ["3.9.13", "3.10", "3.11", "3.12", "3.13", "3.14.0-rc.2"]
        #weewx-version: ["5.0.0", "5.2.0", "branch-master", "branch-development"]
        #python-version: ["3.13"]
        weewx-version: ["5.2.0"]
        include:
          - weewx-version: branch-master
            os-version: ${{inputs.latest-os-version}}
            python-version: ${{inputs.latest-python-version}}

    #uses: weewx-extensions/development_tools/.github/workflows/analyze-test.yml@v2
    uses: ./.github/workflows/analyze-test.yml
    with:
      module-name: ${{inputs.module-name}}
      os-version: ${{matrix.os-version}}
      python-version: ${{matrix.python-version}}
      weewx-version: ${{matrix.weewx-version}}
      latest-os-version: ${{inputs.latest-os-version}}
      latest-python-version: ${{inputs.latest-python-version}}
      latest-weewx-version: '5.2.0'
      pip-list: ${{inputs.pip-list}}
      package-list: ${{inputs.package-list}}
      lint: ${{inputs.lint}}
      unit-test: ${{inputs.unit-test}}
      function-test: ${{inputs.function-test}}
      integration-test: ${{inputs.integration-test}}
      code-coverage: ${{inputs.code-coverage}}
      coveralls-upload: ${{inputs.coveralls-upload}}
      codecov-upload: ${{inputs.codecov-upload}}
      sonar-scan: ${{inputs.sonar-scan}}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
