name: Locally run analyze and test workflow

on:
  workflow_dispatch:
    inputs:
      coveralls-upload:
        required: false
        type: boolean
        default: false
      codecov-upload:
        required: false
        type: boolean
        default: true
      sonar-scan:
        required: false
        type: boolean
        default: false

jobs:
  analyze-test:
    uses: ./.github/workflows/analyze-test.yml
    with:
      module-name: 'simpleclass'
      python-version: '3.9.12'
      weewx-version: '5.1.0'
      latest-python-version: '3.13'
      latest-weewx-version: '5.1.0'
      #pip-list: 'paho-mqtt'
      #package-list: 'mosquitto'
      coveralls-upload: ${{ inputs.coveralls-upload }}
      codecov-upload: ${{ inputs.codecov-upload}}
      sonar-scan: ${{ inputs.sonar-scan }}
      local: 'true'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
