name: Test the analyze and test workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze-test:
    uses: weewx-extensions/development_tools/.github/workflows/analyze-test.yml@master
    with:
      module-name: 'simpleclass'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
