name: Test the analyze and test workflow

on:
  push:
    branches-ignore: [ "master" ]
  workflow_dispatch:

jobs:
  analyze-test:
    uses: ./.github/workflows/analyze-test.yml
    with:
      module-name: 'simpleclass'
      python-version: '3.13'
      weewx-version: '5.1.0'
      latest-python-version: '3.13'
      latest-weewx-version: '5.1.0'
      #pip-list: 'paho-mqtt'
      #package-list: 'mosquitto'
      coveralls-upload: true
      codecov-upload: true
      sonar-scan: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
